  services:
    postgres:
      container_name: postgres-BSN
      image: postgres:latest
      environment:
        POSTGRES_USER: BOOK-NET
        POSTGRES_PASSWORD: LOKESH@!@#
        PGDATA: /var/lib/postgresql/data
        POSTGRES_DB: book_social_network
      volumes:
        - postgres:/data/postgres
      ports:
        - 5432:5432
      networks:
        - spring-bsn
      restart: unless-stopped
    mail-dev:
      container_name: mail-dev-BSN
      image: maildev/maildev
      ports:
        - 1080:1080
        - 1025:1025

  networks:
    spring-bsn:
      driver: bridge

  volumes:
    postgres:
      driver: local

